name: Karate Tests

on:
  push:
    branches:
      - main  # Adjust branch name as per your default branch

jobs:
  test:
    runs-on: windows-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('grocerystore/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Download Chrome Installer
        run: Invoke-WebRequest -Uri 'https://dl.google.com/chrome/install/latest/chrome_installer.exe' -OutFile 'chrome_installer.exe'

      - name: Install Chrome
        run: .\chrome_installer.exe /silent /install  # Install Chrome silently

      - name: Find available port and start Chrome
        id: chrome
        run: |
          $PORT = (Get-Random -Minimum 8000 -Maximum 9999)
          echo "PORT=$PORT" >> $env:GITHUB_ENV
          start chrome --headless --remote-debugging-port=$PORT
        shell: powershell


      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Specify the distribution

      - name: Install dependencies
        run: mvn clean install -DskipTests
        working-directory: grocerystore  # Set the working directory to GroceryStore

      - name: Run cart Scenarios
        working-directory: grocerystore  # Set the working directory to GroceryStore
        run: |
          mvn clean test -Dtest=TestCartRunner -Dmaven.test.failure.ignore=true
         #grocerystore/src/test/java/com/api/automation/cart/TestCartRunner.java
      - name: Generate Karate Test Report
        if: always()  # Always run this step
        run: |
          mkdir -p karate-reports
          cp -r grocerystore/target/karate-reports/* karate-reports/
        
      - name: Upload Karate Test Report
        if: always()  # Always run this step
        uses: actions/upload-artifact@v2
        with:
          name: karate-test-report
          path: karate-reports
